### PR TITLE
Promises w/ api calls based only on {before:}

### PR DESCRIPTION
**Pull request by 100ideas**
comments here https://github.com/romaklimenko/likes/pull/1#issuecomment-195096445

### CODE REVIEW

**Comment by romaklimenko** [comment]
Hi @100ideas, thank you for pull request.

Let me think about it. I tend to keep the code as simple as possible and if likes.js grows from 55 lines to 260 I want to understand a problem we solve with that.

Also I would like to avoid introducing unnecessary dependencies. For example, promises work just fine in latest node.js, why do we need extra dependency for that?

I'm on slow internet this week, so will back to the code few days later.

**Comment by romaklimenko** [comment]
Just to summarize my previous message:
- Could you please remove all commented code and think how to make is simplier, if it is possible.
- Could you please use native node promises and think if we can remove other dependencies.

I didn't test it yet, but hope the code is stable.

**Comment by 100ideas** [comment]
@romaklimenko thanks for your comments, I'll refactor when I have some more time. My first time playing around with promises; it's definitely messy. I'll try to clean it up. The script currently stops at after grabbing 999 likes.

**Comment by 100ideas** [comment]
closing due to age

**Pull request closed without merging**
